[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "verinfast"
version = "0.3.3"
authors = [
  { name="Jason Nichols", email="github@startupos.dev" },
  { name="Sean Conrad", email="github@startupos.dev"}
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: Free for non-commercial use",
    "Operating System :: OS Independent",
]
dynamic=["dependencies"]

[project.urls]
"Homepage" = "https://github.com/StartupOS/verinfast"
"Bug Tracker" = "https://github.com/StartupOS/verinfast/issues"
"Source" = "https://github.com/StartupOS/verinfast"

[project.scripts]
verinfast = "verinfast.agent:main"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
