# This is a sample config for test runs

#baseurl: https://beta.startupos.dev/api/v2
baseurl: http://localhost:4000
should_upload: true
report:
  id: 541
modules:
  code:
    provider: corsis
    git:
      start: 2023-03-28
    dry: false # Flag to just reupload files
  cloud: 
  # - provider: azure
  #   account: d6f7992c-2a21-4a9c-b46b-e70d2c90070d
  #   start: "2023-05-01"
  #   end: "2023-06-01"
  # - provider: aws
  #   account: 436708548746
  #   start: "2023-05-01"
  #   end: "2023-06-01"
repos:
  - git@github.com:StartupOS/small-test-repo.git
#  - git@github.com:rails/rails.git
localrepos:
