# This is a sample config for test runs

#baseurl: https://beta.startupos.dev/api/v2
baseurl: http://localhost:5003
should_upload: true
report:
  id: 541
modules:
  code:
    provider: corsis
    git:
      start: 2022-11-16
    dry: false
  cloud:
    provider: aws
    account: 655761076522
    start: 2023-05-01
    end: 2023-05-31
repos:
  - git@github.com:StartupOS/small-test-repo.git
localrepos:
